### ISSUE TITLE
unable to run tests

### ISSUE THREAD

**Issue by derickbailey** [LeanKit-Labs/whistlepunk#9]
I'm trying to run the tests on my box and getting an odd error:

```
$ npm test

> whistlepunk@0.3.1 test /Users/derickbailey/dev/scott-white/whistlepunk
> gulp test

/Users/derickbailey/dev/scott-white/whistlepunk/node_modules/gulp-jshint/node_modules/jshint/node_modules/lodash/index.js:11240
});
  ^

SyntaxError: Unexpected end of input
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/derickbailey/dev/scott-white/whistlepunk/node_modules/gulp-jshint/node_modules/jshint/src/cli.js:3:25)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
npm ERR! Test failed.  See above for more details.
```

any idea why this might be happening?

**Comment by brianedgerton** [comment]
Is that after a fresh install? We have verified multiple times that it works. Could it be a network issue with `npm` or something?

**Comment by derickbailey** [comment]
apparently it was a bad npm install... deleted the node_modules folder, ran npm install again and it's all working now!
